title: tjrobinson.net
email: tom@tjrobinson.net
description: >-
  My technology and coding blog
baseurl: ""
url: "https://www.tjrobinson.net/"
twitter_username: tjrobinson
github_username:  tjrobinson
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
disqus:
    shortname: tjrobinson